# linear regression multivariate exercise

## Steeps
* 1) Import libraries
* 2) Import the train data file and clean the data 
* 3) Separate features data
* 4) Separate Labels data
* 5) Create a linear Regression model
* 6) Fit the data into the model
* 7) Prediction result


In [1]:
# 1) Import libraries
import pandas as pd
import numpy as np 
from word2number import w2n
from sklearn import linear_model

In [2]:
# 2) Import train data file
train_data = pd .read_csv('hiring.csv')

In [3]:
train_data

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [4]:
# Data cleaning
train_data['experience'].fillna('zero',inplace=True)
train_data['experience'] = train_data['experience'].apply(lambda x: w2n.word_to_num(x) if isinstance(x, str) else x)

score_nan = train_data['test_score(out of 10)'].median()
train_data['test_score(out of 10)'].fillna(score_nan,inplace=True)

In [5]:
train_data

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    8.0                           7      72000
7          11                    7.0                           8      80000

In [6]:
# 3) Separate features data
Feature = train_data.drop('salary($)',axis= 'columns')

In [7]:
Feature

experience  test_score(out of 10)  interview_score(out of 10)
0           0                    8.0                           9
1           0                    8.0                           6
2           5                    6.0                           7
3           2                   10.0                          10
4           7                    9.0                           6
5           3                    7.0                          10
6          10                    8.0                           7
7          11                    7.0                           8

In [8]:
# 4) Separate Labels data
Label = train_data[['salary($)']]

In [9]:
Label

salary($)
0      50000
1      45000
2      60000
3      65000
4      70000
5      62000
6      72000
7      80000

In [10]:
# 5) Creat linear Regression model
lin_reg = linear_model.LinearRegression()

In [11]:
# 6) Fit the data into model
lin_reg.fit(Feature,Label)

LinearRegression()

In [12]:
# 7) Prediction result
experiance = input('Enter experiance:')
test_score = input('Enter test_score(out of 10):')
interview_score = input('Enter interview_score(out of 10):')
lin_reg.predict([[experiance,test_score,interview_score]])

Enter experiance:3
Enter test_score(out of 10):7
Enter interview_score(out of 10):8


C:\Users\Gopi\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\Users\Gopi\anaconda3\lib\site-packages\sklearn\base.py:566: FutureWarning: Arrays of bytes/strings is being converted to decimal numbers if dtype='numeric'. This behavior is deprecated in 0.24 and will be removed in 1.1 (renaming of 0.26). Please convert your data to numeric values explicitly instead.
  X = check_array(X, **check_params)


array([[56737.99126638]])

## Test the formula

In [13]:
lin_reg.coef_

array([[2812.95487627, 1845.70596798, 2205.24017467]])

In [14]:
lin_reg.intercept_

array([17737.26346434])

In [15]:
# y = m1x1 + m2x2 + m3x3
y = 2812.95487627*float(experiance) + 1845.70596798*float(test_score) + 2205.24017467*float(interview_score) +17737.26346434

In [16]:
y

56737.99126637